name: 'dbt_data_eng_project'
version: '1.0.0'
config-version: 2

profile: 'data_eng_project'

model-paths: [ "models" ]
analysis-paths: [ "analyses" ]
test-paths: [ "tests" ]
seed-paths: [ "seeds" ]
macro-paths: [ "macros" ]
snapshot-paths: [ "snapshots" ]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
models:
  dbt_data_eng_project:
    totalPublications:
      +materialized: view
